zzzzz            =  "="   "bhgga"
zzzz="a"
CRLF	= 	%d13.10				       
<aaaaa>= zzzzz %i"       eee_ee " rrrrr  %s" e r t y y uuuuuud" 			CRLF ; CRLF
/ "zz e  e" /  ; azeaz*ezaeezea
thfghghg / erty  ; azeazezaeezea
thfghghg="m m "  ; azeazezaeezea
erty="e t y u u"; yuyuiyu
; zzzzz            =  "="   "bhgga"
<mumble>     =  "%i" "foo bar" / foo
foo=%i"azerty" "fff"
mumbles      =  %i"foo bar" foo
rrrrr= %d13;CR
