=head1 Directory

LGV: La Grande Vadrouille and Gantt files of the project   [execution](http://dorey.sebastien.free.fr/Project/LGV/mapr/Gantt/).

V0: version made before the first release of MAOP.

V1: first version of MAOP (My Album Of Pictures) [execution](https://dorseb.hopto.org/~sdo/cgi-bin/album.cgi).
    it is eclosed too the very first program made to exercise with CGI Perl.

V2: second version of MAOP (My Album Of Pictures). 


MyNavBase: this contains a program to include in a directory and it prints pod files at the bottom of the listing (if README.pod exists) [execution](http://derased.heliohost.org/).


=head1 Branches

master: current

dev: dedicated to future dev and present dev

old: old dev before year 2007. Under it there is the version V0 which is the first version. That was found on old disks...

tests: different kind of tests with pod file or whatever...
