DataBase::=ColumnName EOL (
ColumnValue |
(ColumnValue EOL)*
)
ColumnName::=(Name ColumnSeprator)* Name
ColumnValue::=(Value ColumnSeparator)* Value 
Name::=[a-zA-Z][a-zA-Z0-9 ]+
Value::=[a-zA-Z0-9]+
EOL::= ('\r' '\n' )| '\n'
ColumnDSeparator::= '||'