=head1 Hello world

Directory that contains....


  ,,,,,::::;;;;''''''''++#+';.``  ``.,:;;:,..,,.,;';'''';'::..````````.....``.................,:;''+++
  ,.,,,,,,::::::;;;''''''''+++++':.`   ``.,;:::,.`.,'+#+'';;.` ``..,,,..`````.................,::;''''
  ......,,,,,,:::::::;;;;;;''''+'+++';,`    ``,:;'::,..,''';:;###@@@@@@@@@#+,``....`..........,;''''';
  ..........,.,,,,,,,::::::;;;''''''''+++';,`   ```.,;::.,+#################@@+:`.............,;;'''''
  ..``............,,,,,,,,:::::;;;';''''''+++##:,  `  `'######@@#################:``.........,:;'':'';
  ...``.```..........,,,,,,::::::::;:;;''''''''++##':'######@@@##@@#@@@@#########@#,`........,:;''':,,
  .......`...````.........,,,,,,,,,,,:::::;;;'''''''######@@@@@@@@@####@######@#####'........,:;''''++
  .....``.....```.``..........,...,,,,,,,,,:::;;''+###@@#@@@@@@@@@@@@@@@@@@@@#@#######.......,:;;'''++
  :,....`.`..```````````.................,,,,,::;+#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##@@###,.....,;''''+++
  :;;;;,,..`...``.```````````````............,,'##@#@@@@@@@@@@@@@@@@@@@@@@##@@#@#@######:....,:;''''#'
  ``.,,::;:;:,..`.``````.````..```````..`.....;+##@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#@@@@####:...,;''';'''
  ``````...,:;;;:,,.``````````````````````...;##@##@#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@######;::,.`,,'';,
  ````````````..:;:';;:,....`````````.```.``,####@@#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##+ `.,,::..,;
  `````````````````.,:;';;:,,..```````````..######@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##+` ```.,:::
  ````````````````.`````..:';;'::,.```..``.######@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#@+;:.`.``.
  ```````````````````````.`..,,::;;:::,.``:#####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##''++#';:,
  ``````````````````````````..`````.,;;;;;#####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##+''''''+#
  ```````````````..`````````..`````````..+####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##';''''''
  ```.``````````   `.```````.```````````,#####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#+:::;;;'
  ``   ` `  ````````  ..````````````````'####@#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##;,,::::
  ``  ` ```````````````````.```````````.###@##@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##+.,,,,:
  ` `  ``.,,```````````````````````````:####@@@@#@@@@@@@@@@@@@@@@@#@@@@#@@@@@@@@@@@@@@@@@@@@@###,...,.
  ````::,` ````````````````.```````````+####@@@@@@@@@@@@@@@#@#@@####@@@@@@@@@@@@@@@@@@@@@@@@@@@#:.....
  ``:,````````````````````````````````.######@@@@@@@@@@@@@@########@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'.....
  ````````````````````````````:,.`````,######@@@@@@#@@@@@@@########@@@@@@@@@@@@@@@@@@@@@@@@@@@##'.....
  :,.``..```````.`.`````````````.:,.``;######@@@@@##@@@@@@@######@@@@###@@@@@@@@@@@@@@@@@@@@@@##+.....
  .```````````````````````````..`'''':+######@@@#@####@@@########@@@@@#@@@@@@@@@@@@@@@@@@@@@@@##+.....
  `````````````````````````````..,+++'######@@@@@#####@@#######@#@@@@#@@@@@@@@@@@@@@@@@@@@@@@@##+;,,,.
  ``````````````````````````````.`++++######@@@@@#####@@##################@@@@@@@@@@@@@@@@@@@@@#+:;;;;
  ``````````````````````````````..,+++######@@#####@@@@@@################@@#@@@@@@@@@@@@@@@@@@@#;...::
  ``````````````````.```````````.,.'+#######@#@#@#@@@@@#################@@@@@@@@@@@@@@@@@@@#@@@#,.,,,,
  `````````````````.```````````....:';#####@@@@###@@@@@##############@@@@@@@@@@@@###@###++;'#@#+;,::::
  ...````````````.,.:::;,:..```...,,;;###########@@@@@#############@@@@@@@##@@@@@##@#####++;:+##':::::
  ...``.``````.:::;'+''''''+#;,....,::+#@###@##@@@#@@@##@@@@@@@#@@@@@@@@@@@@@@@@@@#######++#',.++::,,`
  .....``...:+;'''''''''''''+#+',.`.:;'##@##@##:.;####@@@@@@@@#####@@@@@@@@@@@@@@@#######+'+#:.''+++##
  ,...`..,'';;;'''''''''''''++++##+:,;;##@###++;,#+#@@@@@##@@@###@@@@@@@@@@@#@@@@@########+;:'::''+++'
  ,.....;''''''''''''''';;;''+#++##+;;'####+'+++:##@@#@@@@@@@@#####@@@@@@@@@@@@@@@########+':;''';:;''
  ..`.:''';'''';;;;;;;'';;;''+#######'+#+'+######@@@@@@####@@@######@@@@@@@@@@@@@@@@@#####+':,:'';;:;'
  `.,:'';;;;;;;;;;;;;;;;;;;''+########+#'+######@@@@@@@##++@@@#+++++#@@@@@@@@@@@@@@@#######;:,.:'';''+
  .,;':;;:::::::::;;;;;;;;;''+########+#'########@@@@@@@@@##@##+++++##@@@@@@@@@@@@@@######+;:,,.:''+++
  :;;,::::::::,:,:::;:::;;;''++#####@##++####@###@@@@@@@@@@#@#+'''+++###@@@@@@@@@@@@@##@#;:;:,,.,''+++
  :;,,:::,::'+++###++';;;;'''++#######@########@#@@@@@@@@@@@##''''''+++##@@@#+#@@@@###+;::,:;,,,,;;;'+
  :,,,::::;''++++++####+'''''++#######@########@@@@@@@@@@@@@#';;;'''''++####@@####++';::,,,:::,,,;::;;
  ,.,::;;;;'+++++++++####+''+++######@##+'######@@@@@@@@@@@#+;:::;''';;+#######++++'';:,:,,,::,,,''::'
  ..,;''++++++++++++++####+++++#####@@@@+'#######@@@@@##@###';::;'++'';;;'###++++++'';;,::::::..,;';:'
  ..:''++++########++++++++++++#####@@##+'+#########@@@####':;;''+++++++';'##++++++'''';:,:::,...;+':'
  .,;'++#############++++++++++#####@@##+++;++#++########++::'''+++++#@##+'###+#+++++''';:,,;,...:';:'
  .:;'++##############++++++++######@#@##+',.:;'++#+++++++;;'#######@@@@##+#####+++++++'';,,:,....'';'
  ,,;;'++######@######++++++++######@####+;:,::::::,:;;''+;'#@@@#####@@@##########+++++'';,,:,...,,'''
  ,::;'+++#############++++++########@@#+#:,,,,..`..,;'++#;+#@@####################+++++';:,:;...,..;'
  .,:;;'+++######+#####+++++#########@@@#+:,,,,.``.,:''++#+#########################+++++';,:',.....,'
  .,:;;;''++##########+++'''#@@@###@@#@@#':,::,...,:;'++#+++#########################++++';;;':,,.,,,;
  .,,::;;'++++#######++++';'#@@@###@##@@#+:,::...,:;'+++++''++++######################++++';;';,,.,,,:
  ..,::;;++''++#####+++'';::#@@@@##@#@@@#'::;,..,,;'++##++';''+++##############@@######+++'';';:,,,,.,
  .,,:::'+';'''++++++'+';;,:+#@@####@@#@@';;:,,,::;'++###';;;'''+######+#######@@@####+++++'';;;:,,,..
  ,,,::;'+''''''''''''';:,,:'@######@@@@#';;;,,:+;'++###+';'''''+###+++#++++###@#@####+++++'''';::,:,,
  ,::::;++;;''''''''';;:,.,,'##@#@##@@@@+';;,,:;;'++####++'''':;''''++################++++++++';;::;,,
  ::::;'+';;;;''''''';;,...:'#@@@@@@@@@##';;:::;''++####+'';;:;+#########@###@@@@@@##++++++++''';;;;:,
  :::;;+';;''''''''''';,..,:'###@@###@+##;;:::;;''+#####++';;+##########+++###@@@@@##+++++++++'';;;;;:
  ::;;;#';;''''''''+'':.`.,;'########@+##+';::;''++#####++''###++'''+++++++++###@####+++##+++++''';;;:
  ::;;'+;'''''''''++:,.`.,:;'########@'##'';;;'''++######+'#+:::;''++++++++#+########+++##++++'''';;;:
  :::;++;''''''''++',`.,:;'''+######@#'##+';;;''+++########+';;;'++#################++++##++++'''';;;:
  ::::+';''''''''+++'''''+++++######@@'+#';;''''+++######@+;;;'++###########++#######++###++++'''';;;:
  :::;+''''''''''''+++##+'+++#######@#+##';;'''''+++#####+''''++##########++++########+####++++''';;::
  ::::+;''''++'''''++++++++++#########'+#++'+++'''+++####';;'+++#####@@#++++++#######+#####++++'''';::
  ::::';''''''''''''+++++###+#######+';;#+++'++''''++###';;;;''++#';::;''+'++++++##+#######++++''';;:'
  ::::+;'''''''+''''+++++####+#####++':,#+++++++''+++###';;;;;;;:,,,:;;''''''''+++#########+++++'';;;+
  :::;';''''++++++''+++++#####+####'';;;++++''+++++++#++;;;;;;::,,:::;'''''''''+#++########+++++'';:'#
  :::''''+++++++++++++++#####+#++#++;;;;;#+'+'+++++++++';;;;::,,,,::;''+'''''''++++########+++++'';'##
  :::+'''++++###############+++++++''''';#++''+++++++++';;;:,,,:,:;;;''+++++++'''++####+#####+++'''+#+
  :::+'''++++++++##########++++++'+++###+'+#+++++++++++';;:::,,,,;;'''+++++++++'+++##########++'''+###
  ::;+''++++++++++++########+''+'++++###++++#+++++++++''';::::;;;''++++###++++++++###########++''#####
  ::'#'+++++++++++++##+####++;;;::'+++##++++++++++++++';;;;;:;;'''++++######++++++##########++''+####'
  :;:+'+++++++++++#########+';;,,,,:;'+###+#+++++++++'';;;;;;;'''+++#########+#+++##########+++#@@###;
  ++++#######+':,.```...:'++####++++++++''';;;;'''+++++########################++######',
  ++++++++#++,```````..,:;'+++++++++++'''';''+''+++++###########################@#####;:
  ++++++++,`````````..,:;'++'++++++++++''''++'+++++##########################@@####+:,
  '++++++++:` ```````....,:''+++++++++++++'''+++++++##########################@@####+;:,
  ''+++++++'``````.........,;'+++#+++++++++''+'+++#+##########################@@@####'::,
  '+'++++++;;:,,`.....````,:;'++#+++++#++++'++++++########################@@@@@@@##+';;::
  '''+++++++;.;:::...`` `.,;'+++++##++++++++'+''''++++#####################@@@@@@####+';:::
  ''++++++:```,::..````,;++#########+++++++''';'++++++###################@@@@@@@###+';;;;;
  ''+++++++'''+++'`   `:,.....:'+###########@#++++++''''++++++#################@@@@@@@@@@#++';'';;
  ''++++++#####:..```,:,.,:;'+###########@@@+++++++''+++++++###############@@@@@@@@@@@#++';;'';;
  ''++++++####;+#+;,,;;:;;'+###########@@@@@+++++++++++++++###########@##@@@@@@@@@@#@++++'''';;
  '''''++++'####++++#+;;'::;'+###########@@@@@#+++++++++++++++##########@@@@@@@@@@@@##+++''''';,,
  ;;'''''+++++###+++++#+'':,:'#####+#####@@@@@@@#++++++++++++++++######@@@@@@@@@@@@@@#++++'+'';;'#
  ;;;;'''''++#####+++####+',`,'###+'######@@@@@@@@#+++++++++++++++####@#@@@@@@@#####@##+++''++;:'##
  ;;;;'''''+########+#####+,`.;###''++####@@@@@@@@##+++++++++++++####@@@#++#@###@@#@#++++++++;'##@@
  :;;;;;;''''''#########':+###: .:'++++++###@@@@@@@@@@#++++++++++++#####@@@@@######@@@##+++++++'+#@@@@
  ###+###+++++#++++++++####@@#@###++,,:;:,..........,,,,,::,.`..,,,,:;'';;:,,,,,,:::::::'#@@@@#######@
  #########+++#+#++++++####@@#@####;::;;:,..........,,,::;:;.....,,,:;';;;::,,,,,,,,,,::+#@@@@####@@#@
